name = input('Enter the name of character: ')
ch_class = input('Enter the class of character (e.g., Sorcerer, Knight, Archer): ')
home_realm = input('Enter the Home Realm (e.g., “Whispering Woods”): ')
ability = input('Enter the Special Ability of the Character (e.g., “Fireball”): ')
weapon = input('Enter the Character weapon: ')
print(f'\n\n Name: {name}')
print(f'Class: {ch_class}')
print(f'Realm: {home_realm}\n\n')
print(f'Title: {name} the {ch_class} of {home_realm}\n\n')
print(f'\n\n{"-" * 45}')
print(f'Weapon of Choice: {weapon}')
print(f'Special Ability: {ability}')
print(f'{"=" * 50}\n\n')